use_hashing = False
#model_name="TfIdf"
model_name = 'Counter'
path_in="../data/subtitle_debug/"
stop_word_path="stop_words.utf8"
algo_name='KMeans'
max_iter=10
cluster_number=5
top_terms_file='../data/debug/'+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_top_terms.txt"
cluster_out_file="../data/debug/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters.txt"
n_features=10000
n_components=False
minibatch=None
verbose=False
data_lines=None
model_file_name="../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_centers.h5"
label_file_name ="../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_labels.h5"
mode = 'Training'
vectorizer_file_name='../model/'+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_vectorizer.pkl"
