use_hashing = False
#model_name="TfIdf"
model_name = 'Counter'
#model_name = 'FeatureHasher'
path_in="../data/video_90w.dat"
stop_word_path="stop_words.utf8"
algo_name='KMeans'
max_iter=1
cluster_number=10
#top_terms_file='../data/debug/'+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_top_terms.txt"
#cluster_out_file="../data/debug/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters.txt"
#n_features=10000
n_components=False
minibatch=None
verbose=False
data_lines=None
label_file_name ="../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_labels_video_90w"
center_file_name = "../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_centers_video_90w"
mode = 'Training'
#vectorizer_file_name='../model/'+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_vectorizer.pkl"
serilization_mode = 'default'
