use_hashing = False
#model_name="TfIdf"
model_name = 'Counter'
#model_name = 'FeatureHasher'
path_in="../data/subtitle/"
stop_word_path="stop_words.utf8"
algo_name='KMeans'
max_iter=1000
cluster_number=5000
topk=10

top_terms_file='../data/'+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_top_terms"+str(topk)+".txt"
cluster_out_file="../data/"+str(cluster_number)+"_clusters_"+str(max_iter)+str(topk)+"_iters.txt"
#n_features=10000
n_components=False
minibatch=None
verbose=False
data_lines=None
label_file_name ="../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_labels_video"+str(topk)
center_file_name = "../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_centers_video"+str(topk)
mode = 'Training'
serilization_mode = 'default'
feature_dic_path ="../model/"+str(cluster_number)+"_clusters_"+str(max_iter)+"_iters_feature_dict_video"+str(topk)
